#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pysaml2
Version  : 7.2.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/ce/dd/92e47079ef2dd4c91312ebbe6c6ae3b6466e86958f661ea230f73435d7f5/pysaml2-7.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/dd/92e47079ef2dd4c91312ebbe6c6ae3b6466e86958f661ea230f73435d7f5/pysaml2-7.2.1.tar.gz
Summary  : Python implementation of SAML Version 2 Standard
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-pysaml2-bin = %{version}-%{release}
Requires: pypi-pysaml2-license = %{version}-%{release}
Requires: pypi-pysaml2-python = %{version}-%{release}
Requires: pypi-pysaml2-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cryptography)
BuildRequires : pypi(defusedxml)
BuildRequires : pypi(pyopenssl)
BuildRequires : pypi(python_dateutil)
BuildRequires : pypi(pytz)
BuildRequires : pypi(requests)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(six)
BuildRequires : pypi(wheel)
BuildRequires : pypi(xmlschema)

%description
*************************
PySAML2 - SAML2 in Python
*************************
:Version: see VERSION_
:Documentation: https://pysaml2.readthedocs.io/

%package bin
Summary: bin components for the pypi-pysaml2 package.
Group: Binaries
Requires: pypi-pysaml2-license = %{version}-%{release}

%description bin
bin components for the pypi-pysaml2 package.


%package license
Summary: license components for the pypi-pysaml2 package.
Group: Default

%description license
license components for the pypi-pysaml2 package.


%package python
Summary: python components for the pypi-pysaml2 package.
Group: Default
Requires: pypi-pysaml2-python3 = %{version}-%{release}

%description python
python components for the pypi-pysaml2 package.


%package python3
Summary: python3 components for the pypi-pysaml2 package.
Group: Default
Requires: python3-core
Provides: pypi(pysaml2)
Requires: pypi(cryptography)
Requires: pypi(defusedxml)
Requires: pypi(pyopenssl)
Requires: pypi(python_dateutil)
Requires: pypi(pytz)
Requires: pypi(requests)
Requires: pypi(setuptools)
Requires: pypi(six)
Requires: pypi(xmlschema)

%description python3
python3 components for the pypi-pysaml2 package.


%prep
%setup -q -n pysaml2-7.2.1
cd %{_builddir}/pysaml2-7.2.1
pushd ..
cp -a pysaml2-7.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1669612136
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pysaml2
cp %{_builddir}/pysaml2-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pysaml2/be8f3eb13b3dfb0e413a47009022c3c5897b60e8 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/make_metadata.py
/usr/bin/mdexport.py
/usr/bin/merge_metadata.py
/usr/bin/parse_xsd2.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pysaml2/be8f3eb13b3dfb0e413a47009022c3c5897b60e8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
